/****************************************************************************************************************
* Copyright: © 2018-2026 Ozan Nurettin Süel (aka UIManufaktur)
* License: Subject to the terms of the Apache 2.0 license, as written in the included LICENSE.txt file.
* Authors: Ozan Nurettin Süel (aka UIManufaktur)
*****************************************************************************************************************/
module uim.security.auth;

import std.base64 : Base64URLNoPadding;
import std.conv : to;
import std.datetime : Clock, SysTime, SysTimeFromUnixTime;
import std.digest.hmac : hmac;
import std.digest.sha : SHA256;
import std.exception : enforce;
import std.string : format, split;

import uim.security.crypto : constantTimeEquals;

@safe:

struct ApiKey {
  string id;
  string secret;
}

/// Validates provided API key values against allowed keys.
bool validateApiKey(ApiKey[] allowed, string providedId, string providedSecret) @safe {
  foreach (key; allowed) {
    if (constantTimeEquals(key.id, providedId) && constantTimeEquals(key.secret, providedSecret)) {
      return true;
    }
  }
  return false;
}

/// Builds a CSRF token tied to a session and timestamp.
string generateCsrfToken(string secret, string sessionId, SysTime now = Clock.currTime()) {
  enforce(sessionId.length > 0, "sessionId required");
  auto timestamp = now.toUnixTime();
  auto message = sessionId ~ "|" ~ format("%s", timestamp);
  auto sig = hmac!SHA256(cast(const ubyte[]) secret, cast(const ubyte[]) message);
  return format("%s.%s", timestamp, Base64URLNoPadding.encode(sig));
}

/// Verifies a CSRF token generated by `generateCsrfToken` within an optional max age.
bool verifyCsrfToken(string token, string secret, string sessionId, long maxAgeSeconds = 7200, SysTime now = Clock.currTime()) {
  auto parts = token.split('.');
  if (parts.length != 2) {
    return false;
  }

  long timestamp;
  try {
    timestamp = parts[0].to!long();
  } catch (Exception) {
    return false;
  }

  if (maxAgeSeconds > 0 && now.toUnixTime() - timestamp > maxAgeSeconds) {
    return false;
  }

  auto issuedAt = SysTime.fromUnixTime(timestamp);
  auto expected = generateCsrfToken(secret, sessionId, issuedAt);
  return constantTimeEquals(token, expected);
}
