/****************************************************************************************************************
* Copyright: © 2018-2026 Ozan Nurettin Süel (aka UI-Manufaktur UG *R.I.P*) 
* License: Subject to the terms of the Apache 2.0 license, as written in the included LICENSE.txt file. 
* Authors: Ozan Nurettin Süel (aka UI-Manufaktur UG *R.I.P*)
*****************************************************************************************************************/
module uim.errors.enumerations.errors;

enum ERRORS : size_t {
  ERROR = 1, // Fatal run-time errors. These indicate errors that can not be recovered from, such as a memory allocation problem. Execution of the script is halted.
  WARNING = 2, // Run-time warnings (non-fatal errors). Execution of the script is not halted.
  PARSE = 4, // Compile-time parse errors. Parse errors should only be generated by the parser.
  NOTICE = 8, // Run-time notices. Indicate that the script encountered something that could indicate an error, but could also happen in the normal course of running a script.
  CORE_ERROR = 16, // Fatal errors that occur during D's initial startup. This is like an ERRORS.ERROR, except it is generated by the core of D.
  CORE_WARNING = 32, // Warnings (non-fatal errors) that occur during D's initial startup. This is like an ERRORS.WARNING, except it is generated by the core of D.
  COMPILER_ERROR = 64, // Fatal compile-time errors. This is like an ERRORS.ERROR, except it is generated by the Zend Scripting Engine.
  COMPILER_WARNING = 128, // Compile-time warnings (non-fatal errors). This is like an ERRORS.WARNING, except it is generated by the Zend Scripting Engine.
  USER_ERROR = 256, // User-generated error message. This is like an ERRORS.ERROR, except it is generated in UIM code by using the UIM function trigger_error().
  USER_WARNING = 512, // User-generated warning message. This is like an ERRORS.WARNING, except it is generated in UIM code by using the UIM function trigger_error().
  USER_NOTICE = 1024, // User-generated notice message. This is like an ERRORS.NOTICE, except it is generated in UIM code by using the UIM function trigger_error().
  STRICT = 2_048, // Enable to have UIM suggest changes to your code which will ensure the best interoperability and forward compatibility of your code.
  RECOVERABLE_ERROR = 4_096, // Catchable fatal error. It indicates that a probably dangerous error occurred, but did not leave the Engine in an unstable state. If the error is not caught by a user defined handle (see also set_error_handler()), the application aborts as it was an ERRORS.ERRORS.
  DEPRECATED = 8_192, // Run-time notices. Enable this to receive warnings about code that will not work in future versions.
  USER_DEPRECATED = 16_384, // User-generated warning message. This is like an ERRORS.DEPRECATED, except it is generated in UIM code by using the UIM function trigger_error().
  // Future
  BIT16 = 32_768,
  BIT17 = 65_536,
  BIT18 = 131_072,
  BIT19 = 262_144,
  BIT20 = 524_288,
  BIT21 = 1_048_576,
  BIT22 = 2_097_152,
  BIT23 = 4_194_304,
  BIT24 = 8_388_608,
  BIT25 = 16_777_216,
  BIT26 = 33_554_432,
  BIT27 = 67_108_864,
  BIT28 = 134_217_728,
  BIT29 = 268_435_456,
  BIT30 = 536_870_912,
  BIT31 = 1_073_741_824,
  BIT32 = 2_147_483_648,
  BIT33 = 4_294_967_296,
  BIT34 = 8_589_934_592,
  BIT35 = 17_179_869_184,
  BIT36 = 34_359_738_368,
  BIT37 = 68_719_476_736,
  BIT38 = 137_438_953_472,
  BIT39 = 274_877_906_944,
  BIT40 = 549_755_813_888,
  BIT41 = 1_099_511_627_776,
  BIT42 = 2_199_023_255_552,
  BIT43 = 4_398_046_511_104,
  BIT44 = 8_796_093_022_208,
  BIT45 = 17_592_186_044_416,
  BIT46 = 35_184_372_088_832,
  BIT47 = 70_368_744_177_664,
  BIT48 = 140_737_488_355_328,
  BIT49 = 281_474_976_710_656,
  BIT50 = 562_949_953_421_312,
  BIT51 = 1_125_899_906_842_624,
  BIT52 = 2_251_799_813_685_248,
  BIT53 = 4_503_599_627_370_496,
  BIT54 = 9_007_199_254_740_992,
  BIT55 = 18_014_398_509_481_984,
  BIT56 = 36_028_797_018_963_968,
  BIT57 = 72_057_594_037_927_936,
  BIT58 = 144_115_188_075_855_872,
  BIT59 = 288_230_376_151_711_744,
  BIT60 = 576_460_752_303_423_488,
  BIT61 = 1_152_921_504_606_846_976,
  BIT62 = 2_305_843_009_213_693_952,
  BIT63 = 4_611_686_018_427_387_904,
  BIT64 = 9_223_372_036_854_775_808,
  ALL = 18_446_744_073_709_551_615
}
