/****************************************************************************************************************
* Copyright: © 2018-2026 Ozan Nurettin Süel (aka UIManufaktur) 
* License: Subject to the terms of the Apache 2.0 license, as written in the included LICENSE.txt file. 
* Authors: Ozan Nurettin Süel (aka UIManufaktur)
*****************************************************************************************************************/
module uim.core.containers.sequential.arrays.group;

import uim.core;

mixin(ShowModule!());

@safe:

/** 
  * Groups elements of an array based on a key generated by a provided function.
  *
  * Params:
  *   values = The input array to be grouped.
  *   keyFunc = A function that takes an element and returns a key for grouping.
  *
  * Returns:
  *   A associative array where each key maps to an array of elements that share that key.
  */
V[][K] groupBy(T, K, V)(T[] values, K delegate(T) @safe keyFunc, V delegate(T) @safe valueFunc) {
  V[][K] results;
  foreach (item; values) {
    K key = keyFunc(item);
    V value = valueFunc(item);
    if (key !in results) {
      results[key] = [];
    }
    V[] buffer = results[key];
    buffer ~= value;
    results[key] = buffer;
  }
  return results;
}
///
unittest {
  mixin(ShowTest!"Testing groupBy");

  // Define a struct for testing
  struct Person {
    string name;
    int age;
  }

  // Sample data
  Person[] people = [
    Person("Alice", 30),
    Person("Bob", 25),
    Person("Charlie", 30),
    Person("David", 25),
    Person("Eve", 35)
  ];

  // Group people by age, collecting their names
  auto grouped = groupBy!(Person, int, string)(
    people,
    (Person p) => p.age,
    (Person p) => p.name
  );

  // Verify the grouping
  assert(grouped.length == 3);
  assert(grouped[25].equal(["Bob", "David"]));
  assert(grouped[30].equal(["Alice", "Charlie"]));
  assert(grouped[35].equal(["Eve"]));
}
